src/MenuItem.jsx
src/SubMenu.jsx

MenuItem/SubMenu 增加 `onMouseEnter/onMouseLeave` 事件，只在 `mode: inline` 时生效。
ant-design/ant-design#1445

support `onMouseEnter/onMouseLeave` for MenuItem and SubMenu

---

src/Menu.jsx

https://github.com/ant-design/ant-design/issues/1746

Fix children render with containing `null` (or similar) item

---

src/DOMWrap.jsx
src/Divider.jsx
src/MenuItem.jsx
src/MenuMixin.js
src/SubMenu.jsx
src/SubMenuStateMixin.jsx

1. https://github.com/ant-design/ant-design/issues/2258
2. rc-util warnings

Fix some warnings

---

src/MenuMixin.js

```
function renderAdminMenu(){
if(isAdmin){
return <SubMenu>.......</SubMenu>;
}
return;
}
<Menu>
<SubMenu key="a">......</SubMenu>
{this.renderAdminMenu()}
<Menu.Item>......</Menu.Item>
</Menu>
修复当使用上面的代码时会因为renderAdminMenu 返回的是null,
报Uncaught TypeError: Cannot read property 'props' of null

[fix] cannot read preperty of null

---

package.json
src/SubMenu.jsx

aria-open => aria-expanded
`aria-open` is not a valid aria prop: https://www.w3.org/TR/wai-aria-1.1/#global_states
ant-design/ant-design#3882

Fix aria warning in react@15.4.0

---

src/SubPopupMenu.js

错误信息：Uncaught TypeError: Cannot read property 'key' of null
示例：http://codepen.io/skyriver9/pen/vybwZM?editors=0010
导航 - 子菜单2

fix: when subMenu's children is null

---

README.md

I needed the selectable prop and had to read the source code to see there was an option here. 
https://github.com/react-component/menu/issues/33

Add selectable option into Menu doc

---

.travis.yml
package.json

As far as I can tell there are no breaking changes that affect `rc-menu`
This change can solve some issues where `rc-util` 3.x is required by another module. It solves this: (as long as you don't have any other rc components that use rc-util 3.x) https://github.com/react-component/trigger/issues/34

Update rc-util version to 4.x

---

assets/index.less
examples/keyPath.js
examples/multiple.js
examples/openKeys.js
examples/scrollable.js
examples/selectedKeys.js
examples/single.js
src/SubMenu.jsx
tests/__snapshots__/Menu.spec.js.snap

1. subMenu 统一添加箭头， clsssName 为 arrow;
2. 修复 demo 报错。。。

unified arrow

---

src/Menu.jsx
src/MenuMixin.js
tests/MenuItem.spec.js
tests/SubMenu.spec.js

close ant-design/ant-design#8567
It is not reasonable to clear openKeys and selectedKeys when submenu destroy

Keep state when submenu destroy

---

package.json
src/Menu.jsx
src/MenuItem.jsx
src/MenuItemGroup.jsx
src/MenuMixin.js
src/SubMenu.jsx
src/SubPopupMenu.js
src/util.js
tests/SubMenu.spec.js

Using mini store to subscribe local change to improve performance.
Before:
After:
Notes: 
1. Every menu and subMenu have to keep their own entrance in mini store for both activeKey and defaultActiveFirst configuration.
2. All unit tests passed and verified carefully that all behaviors are identical to previous version.
TODO items:
1. We wanted to get rid of mixin once for all, but it was too big change to go with this one. Not confident enough to do that refactor yet...
2. Mini Store does not support setState callbacks, might need some help. But it should be a very minor thing.

perf: refactor to avoid unnecessary re-render with mini-store

---

src/SubMenu.jsx
tests/SubMenu.spec.js

每次render instanceArray都会被置空：
https://github.com/react-component/menu/blob/master/src/MenuMixin.js#L214
所以submenu的saveRef也应该在componentDidUpdate里

fix: keyboard navigation not working after mounted

---

src/DOMWrap.jsx
src/Menu.jsx
src/MenuItem.jsx
src/MenuItemGroup.jsx
src/MenuMixin.js
src/SubMenu.jsx
src/SubPopupMenu.js
src/util.js
tests/Menu.spec.js
tests/MenuItem.spec.js
tests/SubMenu.spec.js
tests/__snapshots__/Menu.spec.js.snap

chore: improve coverage and one minor bug fix

---

src/MenuItem.jsx
src/SubMenu.jsx
src/SubPopupMenu.js
tests/Menu.spec.js
tests/MenuItem.spec.js
tests/__snapshots__/Menu.spec.js.snap
tests/__snapshots__/MenuItem.spec.js.snap

https://github.com/ant-design/ant-design/issues/10095
The idea is to fix the area-* attributes issue and avoid any breaking changes
before:
after:

chore: fix aria-* attirbutes

---

src/MenuItem.jsx
tests/MenuItem.spec.js
tests/__snapshots__/MenuItem.spec.js.snap

This will remove the implied `listitem` role of the `<li />`.
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html
Related to this original issue:
https://github.com/ant-design/ant-design/issues/10095
Sorry, I'm just learning all about proper accessibility.

On MenuItem, set the `role` to `none` if the role is `null` or `none`.

---

src/Divider.jsx

addressing https://github.com/react-component/menu/issues/168

feat: allow customize divider style via style props

---

src/DOMWrap.jsx

A quick fix for ant.design site console error. A thorough fix will be included in https://github.com/react-component/menu/pull/172

fix: preventive check in setChildrenSize

---

README.md
assets/index.less
examples/antd.js
package.json
src/DOMWrap.jsx
src/Divider.jsx
src/Menu.jsx
src/SubMenu.jsx
src/SubPopupMenu.js
src/util.js
tests/Menu.spec.js
tests/SubMenu.spec.js
tests/__mocks__/mutationobserver-shim.js
tests/__snapshots__/Menu.spec.js.snap
tests/__snapshots__/MenuItem.spec.js.snap

todo item: try not to apply overflow: hidden on root menu.

Redo overflow

---

README.md

I saw that the word vertical does not use <th> tag. I just made it consistent with other default value in the table.

Fix: made default mode 'vertical' to be center

---

package.json

`rc-table` 更新 mini-store 2.0.0，同步更新 mini-store 到相同版本，否则会出现 menu 和 table 引用两个不同版本的 mini-store。

:arrow_up: Bump mini-store to 2.0.0

---

src/util.js

FIx https://github.com/ant-design/ant-design/issues/14007

 Set the same precision for chrome and firefox

---

src/SubMenu.jsx

not (`!`) binds more tightly than equality comparisons, so the third clause in this expression is incorrect:
https://github.com/react-component/menu/blob/a540719c46a274641d618bfa5d121360d3ed9f54/src/SubMenu.jsx#L388-L391
`!baseProps.mode === 'inline'` is equivalent to `(!baseProps.mode) === 'inline'` which will always equal false, as neither `true` nor `false` are exactly equal to `'inline'`.
I found this problem on the [alert list for this project on LGTM.com](https://lgtm.com/projects/g/react-component/menu/alerts), while going through results. The only other remaining alerts are 2 alerts that are in example code.
*(Full disclosure: I'm part of the team behind LGTM.com)*

[chore] fix logical error in SubMenu.jsx

---

examples/selectedKeys.js

I know that this is just in example code, but given that these are the only two alerts remaining for this project on LGTM, I thought it's probably worth the PR :)
React component state updates using `setState` may asynchronously update `this.props` and `this.state`, thus it is not safe to use either of the two when calculating the new state passed to `setState`, and instead the callback-based variant should be used instead. ([details here](https://lgtm.com/rules/1819283066/)).
These were [found on LGTM.com](https://lgtm.com/projects/g/react-component/menu/alerts), and other than the alert fixed in #230, there are no remaining alerts.
*(Full disclosure: I'm part of the team behind LGTM.com)*

🚨 fix inconsistent component state updates in example code

---

src/MenuItem.jsx

问题： 所有 Select 键盘操作都无法滚动到 active item 上了。
close ant-design/ant-design#18939
https://github.com/react-component/menu/commit/452dc7f8665e99c4247cc8fd078e3b868cc088d1

fix: active item cannot be scrolled

---

src/MenuItemGroup.tsx

As it is specified in the documentation, the property title of the MenuItemGroup should support string and ReactElement types. This was not the case as just the string type was mentionned.

added ReactElement type for title prop in MenuItemGroupProps

---

src/SubMenu.tsx

Ref: https://github.com/ant-design/ant-design/pull/19498#issuecomment-548831476

Fix trigger repeat animation

---

README.md
assets/index.less
examples/rtl-antd.js
src/Menu.tsx
src/MenuItem.tsx
src/SubMenu.tsx
src/SubPopupMenu.tsx
src/placements.ts
tests/Menu.spec.js
tests/__snapshots__/Menu.spec.js.snap

Rtl layout support for menu component. as this component used in ant-design and i'm working on [ant-desing rtl repo](https://github.com/ant-design/ant-design/pull/19380) to make ant-design support rtl direction.
Please review and merge these changes as soon as possible, so i can include it in rtl implementation of ant-design.
changes the menu direction with `direction='rtl'` property.
- added some tests.
- added rtl demo
- updated readme

Implemented rtl layout support

---

assets/index.less
src/Menu.tsx
src/MenuItem.tsx
src/MenuItemGroup.tsx
src/SubMenu.tsx
src/SubPopupMenu.tsx
tests/__snapshots__/Menu.spec.js.snap

Patch rtl issues on menu.
1. removed additional attribute from DOM
2. fixed padding issue.
3.change additional usage of store mentioned by @zombieJ [here](https://github.com/react-component/menu/pull/296#issuecomment-553716165)

patch rtl issues

---

src/DOMWrap.tsx

[#23956](https://github.com/ant-design/ant-design/issues/23956)
目前加的防抖时间是100毫秒。

fix: add requestAnimationFrame to resizeObserver(#23956);

---

package.json
src/Menu.tsx
src/utils/legacyUtil.ts
tests/Menu.spec.js

[#24975](https://github.com/ant-design/ant-design/issues/24975)
将 antd 的 menu 中的功能移植过来，自己做状态管理，使其中的 `mini-store` 做的优化渲染在 antd 中生效。
@afc163 @zombieJ 看看有没有遗漏的？

refactor: move features from menu of antd(#24975)

---

src/Menu.tsx
src/index.tsx
src/utils/legacyUtil.ts
tests/Menu.spec.js

@zombieJ @afc163  修改了默认 motion 逻辑、添加了导出 props，看看没问题的话再发一下，我在 antd 里再测测。

chore: optimize logic of  default motion

---

src/MenuItem.tsx
src/index.tsx

- 添加了 `MenuItemProps` 和 `SubMenuProps` 导出
- 优化了 `MenuItem` 的 `props` 声明

types:  add export of  MenuItemProps and SubMenuProps and optmize props of MenuItem

---

src/DOMWrap.tsx
src/Menu.tsx
src/MenuItem.tsx
src/MenuItemGroup.tsx
src/SubMenu.tsx
src/SubPopupMenu.tsx
src/util.ts
src/utils/legacyUtil.ts
tests/Menu.spec.js

close https://github.com/ant-design/ant-design/issues/29429

fix: duplicated selected menu item when selectedKeys is string

---

src/MenuItem.tsx
src/SubMenu/index.tsx
src/utils/nodeUtil.ts
tests/SubMenu.spec.js

resolve https://github.com/ant-design/ant-design/issues/30677

fix:Not warning if content do not need key

---

src/Menu.tsx
src/MenuItem.tsx
tests/Menu.spec.js
tests/__snapshots__/Keyboard.spec.tsx.snap
tests/__snapshots__/Menu.spec.js.snap
tests/__snapshots__/MenuItem.spec.js.snap
tests/__snapshots__/Responsive.spec.tsx.snap

Menu `keyPath` 居然是反过来的，史前巨坑呐。
ref https://github.com/ant-design/ant-design/issues/30733
ref https://github.com/react-component/menu/blame/1870b7943426f2357f74759b2e843707d94a3894/src/SubMenu.jsx#L289

fix: keyPath is inverse

---

src/Menu.tsx
src/SubMenu/PopupTrigger.tsx
src/context/MenuContext.tsx
src/interface.ts
tests/SubMenu.spec.js
tests/__snapshots__/SubMenu.spec.js.snap

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
https://github.com/ant-design/ant-design/issues/34318
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add `rootClassName`     |
| 🇨🇳 Chinese |    添加 `rootClassName`       |
⚠️ Please check all items below before review. ⚠️

feat: add rootClassName

---

src/Menu.tsx

Improve performance via cache
relate: https://github.com/ant-design/ant-design/issues/32681

performance: cache children to improve performance

---

src/hooks/useDirectionStyle.ts
tests/__snapshots__/Keyboard.spec.tsx.snap
tests/__snapshots__/Menu.spec.js.snap
tests/__snapshots__/MenuItem.spec.js.snap
tests/__snapshots__/Options.spec.tsx.snap

现在 `inlineIndent` 设置后会造成菜单整体偏移，应该[忽略顶级菜单偏移](https://github.com/react-component/menu/issues/342)！
resolve https://github.com/ant-design/ant-design/issues/36811

feat: Ignore top level indent

---

src/index.ts

ref: https://github.com/PlasmoHQ/plasmo/discussions/187 https://github.com/ant-design/parcel-antd/pull/25

fix: parcel build error

---

src/Menu.tsx
tests/React18.spec.tsx
tests/util.ts

Reverts react-component/menu#537

Revert "fix: SubMenu in React18 sync problem"

---

assets/index.less

Fix #437 
May fix #422 
The cause is `rc-menu-submenu-hidden`'s style is not included in `index.css`, it should be `display: none`.
If this still does not fix the issue, manually add the style `display: none` for className `rc-menu-submenu-hidden`
---
P.S. Corresponding style is present in `menu.less` but I guess it's not compiled into `index.css` for some reason.

fix: Submenu now properly hide when mouse exits

---

src/SubMenu/index.tsx
tests/Collapsed.spec.js

切换 inline mode 后菜单栏点击展开最深层会出现上个 mode 的弹窗
ant-design 相关 issues https://github.com/ant-design/ant-design/issues/36636
https://user-images.githubusercontent.com/38420763/180976679-112d962d-ab0f-4785-b250-5018f66ebeb6.mp4

fix menu popuptrigger flicker

---

src/Menu.tsx

修复 React18 中使用 createRoot 渲染 Submenu 会闪烁
https://github.com/ant-design/ant-design/issues/38534
<a href="https://codesandbox.io/s/y2pnuc" rel="nofollow"><img src="https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667" alt="Edit on CodeSandbox" data-canonical-src="https://codesandbox.io/static/img/play-codesandbox.svg" style="max-width: 100%;"></a>
https://user-images.githubusercontent.com/38420763/202225387-0e068960-d871-4c2d-ae96-eb8c251a2932.mov
关键代码最小化：
```jsx
const Menu = ({ mode, inlineCollapsed, defaultOpenKeys }) => {
const [mergedOpenKeys, setMergedOpenKeys] = React.useState(defaultOpenKeys);
const [mergedMode, …
```

fix: react18 submenu flicker

---

src/Menu.tsx

fix https://github.com/ant-design/ant-design/issues/38818

fix: force trigger mouse event change

---

src/MenuItemGroup.tsx
src/SubMenu/SubMenuList.tsx
tests/__snapshots__/Keyboard.spec.tsx.snap
tests/__snapshots__/Menu.spec.js.snap
tests/__snapshots__/MenuItem.spec.js.snap
tests/__snapshots__/Options.spec.tsx.snap
tests/__snapshots__/SubMenu.spec.js.snap

Using the axe a11y chrome plugin - some a11y concerns are surfaced. 
Basically when using `role="menu"` the dom hierarchy is very specific.  If additional elements exist between what's expected, they should have `role="presentation` or `role="none"` so screen readers know to ignore them.
**Before**
**After**

fix(a11y): ]  MenuItemGroup, SubMenuList add some role attributes for improved a11y

---

src/SubMenu/PopupTrigger.tsx
tests/Menu.spec.js

这是个祖传bug，一两年前就有这个问题
https://github.com/ant-design/ant-design/issues/39283
mode 为 vertical 和 horizontal 才需要用到 PopupTrigger，
快速切换时 inline 的 Motion 会影响到 vertical 的结束动画。

fix: vertical animation not being affected by inline

---

src/MenuItem.tsx

fix: https://github.com/ant-design/ant-design/issues/41395
原因：由于在非 `SubMenu` 上使用了 `popupClassName` 属性，在整个过程中没有进行处理，最终该属性会被设置到 DOM 元素上去，但是 React 不识别 DOM 元素非标准的属性，因此出现报错。
解决方案：将  `popupClassName`  等一些未使用到的非标准的属性进行过滤。

fix: Resolve console error when MenuItem uses popupClassName

---

src/MenuItem.tsx
tests/React18.spec.tsx
tests/Responsive.spec.tsx

As antd internal patch ref on Menu.Item. We need make it support ref. It's safe to remove after refactor.
fix https://github.com/ant-design/ant-design/issues/41570

fix: Menu.Item not support ref

---

src/MenuItemGroup.tsx
src/SubMenu/index.tsx
src/utils/commonUtil.ts
src/utils/nodeUtil.tsx

https://github.com/ant-design/ant-design/pull/42750
- (undefined) Circular dependency detected:
node_modules/rc-menu/es/Menu.js -> node_modules/rc-menu/es/SubMenu/index.js -> node_modules/rc-menu/es/utils/nodeUtil.js -> node_modules/rc-menu/es/index.js -> node_modules/rc-menu/es/Menu.js @kiner-tang
- (undefined) Circular dependency detected:
node_modules/rc-menu/es/MenuItemGroup.js -> node_modules/rc-menu/es/utils/nodeUtil.js -> node_modules/rc-menu/es/index.js -> node_modules/rc-menu/es/MenuItemGroup.js @kiner-tang
- (undefined) Circular dependency detected:
node_modules/rc-menu/es/SubMenu/index.js -> node_modules/rc-menu/es/utils/nodeUtil.js -> node_modules/rc-menu/es/index.js -> node_modules/rc-menu/es/Menu.js -> node_modules/rc-menu/es/SubMenu/index.js @kiner-tang
- (undefined) …

refactor: solve menu circular dependency issue

---

src/Divider.tsx
tests/Menu.spec.tsx
tests/__snapshots__/Menu.spec.tsx.snap
tests/__snapshots__/Options.spec.tsx.snap

To help rc-menu comply to WCAG 2.1 better, current if scan the page with axe devtool we have this error on a11y:
I have decided to keep this role param fixed because this seem like the only approriate for the divider

feat: support a11y for menu divider

---

docs/examples/debug.tsx
docs/examples/single.tsx

close https://github.com/react-component/menu/security/code-scanning/4
close https://github.com/react-component/menu/security/code-scanning/2

fix: Unused variable, import, function or class

---

src/interface.ts

ref: [ant-design/ant-design#47260](https://github.com/ant-design/ant-design/issues/47260)
```
items.forEach((item) => {
console.log(item.type) // "submenu" | "item" | "group" | "divider"
})
```

feat: add `type` to SubMenuType and MenuItemType

---

README.md
docs/demo/items-ref.md
docs/examples/items-ref.tsx
src/MenuItem.tsx
src/MenuItemGroup.tsx
src/SubMenu/index.tsx
src/interface.ts
tests/Menu.spec.tsx

ref: [ant-design/ant-design#45553](https://github.com/ant-design/ant-design/issues/45553)

feat: MenuItem, MenuGroup and SubMenu support ref

---

src/hooks/useKeyRecords.ts
tests/SubMenu.spec.tsx

close https://github.com/react-component/menu/issues/719
close https://github.com/ant-design/ant-design/issues/49106

fix: active wrong when submenus has key ''

---

assets/index.less
docs/examples/items.tsx
src/Menu.tsx
src/interface.ts
src/utils/nodeUtil.tsx
tests/MenuItem.spec.tsx
tests/__snapshots__/MenuItem.spec.tsx.snap

https://github.com/ant-design/ant-design/issues/49127

feat: support extra option

---

src/utils/nodeUtil.tsx
tests/MenuItem.spec.tsx
tests/__snapshots__/MenuItem.spec.tsx.snap

老大，有空麻烦合并下，递归的时候忘记传参数了 @afc163 
https://github.com/react-component/menu/pull/734

fix: recursion lose prefixCls
