react-component/menu

lib/MenuItem.js
=> fix menuitem active state

examples/antd.js, examples/keyPath.html, examples/keyPath.js, src/SubMenu.jsx
增加 `keyPath` 以实现 [手风琴效果](http://ant.design/components/collapse/#demo-accordion)
=> feat: add `keyPath` for `onOpen/onClose`'s param

src/MenuMixin.js
related #https://github.com/react-component/select/pull/59
=> fix receiving activeKey

src/SubMenu.jsx
`onMouseEnter` should be `onTitleMouseEnter`
=> Fix wrong mouseenter method on submenu title

assets/index.less, src/Menu.jsx, src/SubMenu.jsx, src/SubPopupMenu.js
相关issue：
https://github.com/ant-design/ant-design/issues/2414
=> 选中子菜单时父菜单增加选中样式

README.md
There is a typo in README file.
=> Typo bug fix

src/MenuMixin.js
Close: https://github.com/ant-design/ant-design/issues/3599
=> fix: the children of menu could be null

src/util.js
=> Remove timestamp in child key

src/Menu.jsx
=> added guard clause agains undefined selectedKeys and openKeys

examples/antd.js, examples/keyPath.js, examples/openKeys.js, examples/scrollable.js, examples/selectedKeys.js, package.json, src/DOMWrap.jsx, src/Divider.jsx, src/Menu.jsx, src/MenuItem.jsx, src/MenuItemGroup.jsx, src/MenuMixin.js, src/SubMenu.jsx, src/SubPopupMenu.js
- upgrade to  react 15.5  
- import  createReactClass prop-types
=> Fix react 15.5 warning

src/MenuMixin.js
支持 https://github.com/react-component/select/pull/218
=> Add keydown callback

README.md, package.json, src/Menu.jsx, src/MenuMixin.js, src/SubMenu.jsx, src/SubPopupMenu.js
ref: https://github.com/ant-design/ant-design/issues/5586
=> feat: support forceSubMenuRender

examples/menuItemGroup.js, src/MenuItemGroup.jsx, tests/__snapshots__/Menu.spec.js.snap, tests/__snapshots__/MenuItem.spec.js.snap
=> indent item group title

assets/index.less
https://github.com/react-component/menu/issues/206
The error is gone, but not confident about the fix, please take a look.
=> fix: use cdnjs for @font-face resource , fixing #206

src/DOMWrap.jsx, tests/Menu.spec.js
https://github.com/ant-design/ant-design/issues/12687
=> fix: remove horizontal scrollbar by using display:none

examples/menuItemGroup.js, src/MenuItemGroup.jsx, tests/__snapshots__/Menu.spec.js.snap, tests/__snapshots__/MenuItem.spec.js.snap
Reverts react-component/menu#201
To solve https://github.com/ant-design/ant-design/issues/12715
=> Revert "indent item group title"

src/SubPopupMenu.js, tests/SubPopupMenu.spec.js
ref: https://github.com/ant-design/ant-design/issues/13234
Support change `activeKey` of store when it changed from props.
=> update activeKey when changed

package.json, src/SubPopupMenu.js, src/util.js
Fix https://github.com/ant-design/ant-design/issues/13943
Relate to https://github.com/ant-design/ant-design/issues/12486#issuecomment-449065739
=>  Set default trigger action to click on moible device

src/DOMWrap.jsx, src/util.js
ref: https://github.com/react-component/menu/pull/240
=> fix: float number calculation

src/DOMWrap.jsx
Fix https://github.com/ant-design/ant-design/issues/15179
=> Remove duplicate eventKey

src/MenuItem.jsx
close https://github.com/ant-design/ant-design/issues/16181
只滚动到同名的 Item 的第一个。
=> Fix menu active scroll

package.json
Reverts react-component/menu#273
close #276
close #275
=> Revert "build(deps): update ismobilejs requirement from ^0.5.1 to ^1.0.2"

package.json, src/DOMWrap.tsx, src/SubMenu.tsx, src/interface.ts, tests/Menu.spec.js, tests/__mocks__/mutationobserver-shim.js
ref  https://github.com/ant-design/ant-design/issues/19169
=> refactor: Use `rc-trigger` v4

src/Menu.tsx
Ref: https://github.com/react-component/mentions/pull/18
=> fix: ts type

src/DOMWrap.tsx
Looks like a failed copy/paste of mutationObserver
=> Fix invalid call to resizeObserver

README.md
=> fix:URL bug on README

README.md
resolve: https://github.com/react-component/menu/issues/312
=> docs: fix type of activeKey in doc

package.json
ref https://github.com/ant-design/ant-design/issues/22638
试了一下，没什么问题。帮忙 double confirm 一下。
=> chore: bump mini-store

package.json, src/MenuItem.tsx, tests/MenuItem.spec.js
Remove menuItem scroll into view feaature.
Relative issue: https://github.com/ant-design/ant-design/issues/23936
=> feat: Remove menuItem scroll-into-view feature

.eslintrc.js, src/MenuItem.tsx
close https://github.com/ant-design/ant-design-pro/issues/6693
=> 🐛 bug: fix title=false,will throw warning

src/DOMWrap.tsx, src/util.ts, tests/Menu.spec.js
fix https://github.com/ant-design/ant-design/issues/26337
=> fix: margin is not considered as item width

examples/inlineCollapsed.js, examples/inlineCollapsed.less, src/SubMenu.tsx, tests/Menu.spec.js, tests/SubMenu.spec.js
https://github.com/ant-design/ant-design/issues/26816
https://github.com/ant-design/ant-design/issues/21666
=> fix: inlineCollapsed animation by unify dom structure

src/Menu.tsx
与文档保持一致: https://github.com/react-component/menu/blob/db8eb937e87dd7e1782b110c13740b527086ed5b/README.md
相关 PR: https://github.com/ant-design/ant-design/pull/26581
=> types: update MenuProps onOpenChange type

src/Menu.tsx, tests/Menu.spec.js
close https://github.com/ant-design/ant-design/issues/26905
=> fix: move updateOpentKeysWhenSwitchMode to getDerivedStateFromProps hook

package.json, src/SubMenu.tsx
ref https://github.com/ant-design/ant-design/issues/26979
=> refactor: Align motion with `rc-trigger`

src/Menu.tsx, tests/Menu.spec.js
fix https://github.com/ant-design/ant-design/issues/28714
=> fix: openKeys should allow to be empty

docs/examples/debug.tsx, package.json, src/SubMenu/PopupTrigger.tsx, src/SubMenu/index.tsx
ref https://github.com/ant-design/ant-design/pull/30382#issuecomment-834022492
=> fix: Align width

src/Menu.tsx, tests/Menu.spec.js
resolve https://github.com/ant-design/ant-design/issues/30665
=> fix: !multiple menu should click to close

src/Menu.tsx, tests/Collapsed.spec.js
resolve https://github.com/ant-design/ant-design/issues/30698
=> fix: Vertical also support inlineCollapsed

src/Menu.tsx, tests/Menu.spec.js
resolve https://github.com/ant-design/ant-design/issues/30710
=> fix: Whatever selectable, should close it

src/SubMenu/index.tsx, tests/SubMenu.spec.js
resolve https://github.com/ant-design/ant-design/issues/30746
=> fix: layout mode of className

src/Menu.tsx, src/MenuItem.tsx, src/context/PrivateContext.ts, tests/Private.spec.js
=> chore: support internal props

src/Menu.tsx, tests/React18.spec.tsx
ref https://github.com/ant-design/ant-design/pull/37046
=> fix: Menu defaultOpenKeys not work in React18

package.json
There are critical updates that need to be used.
https://github.com/react-component/overflow/commits/master
=> Update rc-overflow to 1.2.8

src/Menu.tsx, tests/React18.spec.tsx, tests/util.ts
close https://github.com/ant-design/ant-design/issues/38241
=> fix: SubMenu in React18 sync problem

package.json
=> chore: bump rc-overflow

docs/examples/inlineCollapsed.tsx, src/SubMenu/PopupTrigger.tsx, tsconfig.json
close https://github.com/ant-design/ant-design/issues/45160
=> fix: popup should unmounted in inline mode

docs/examples/debug.tsx, src/Menu.tsx, tests/Menu.spec.tsx
fix item focus broken in #671.
close #679
=> fix: fix menu item focus

README.md
https://github.com/react-component/menu/pull/734
=> docs: add extra prop
